# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        #handler_id: null
        handler_id: '%env(REDIS_URL)%'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 86400
        gc_probability: 95
        gc_divisor: 100
        gc_maxlifetime: 600

    #esi: true
    #fragments: true
    php_errors:
        log: true
