# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem

    data_loader: flysystem_loader

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem
                cache_prefix: media/cache
                root_url: '%app.uploads_base_url%'

        # default cache resolver for saving thumbnails
    #        cache: flysystem_resolver

    filter_sets:
        #
        #        # an example thumbnail transformation definition
        #        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        avatar_thumbnail_60_60:
            filters:
                thumbnail:
                    size: [ 60, 60 ]
                    mode: inset
                    allow_upscale: true

        squared_thumbnail_small:
            filters:
                thumbnail:
                    size: [ 80, 80 ]
                    mode: inset
                    allow_upscale: true

        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [ 200, 200 ]
                    mode: inset
                    allow_upscale: true

        home_post_image_card_thumbnail:
            filters:
                thumbnail:
                    size: [ 300, 150 ]
                    mode: inset
                    allow_upscale: true

        view_post_image_thumbnail:
            filters:
                thumbnail:
                    size: [ 960, 450 ]
                    mode: inset
                    allow_upscale: true

