monolog:
    channels:
        - file_upload
    handlers:
        security:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/security/auth.%kernel.environment%.log"
            level: debug
            channels: [ "security" ]
        file_upload:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/file_upload/file_upload.%kernel.environment%.log"
            level: debug
            channels: [ "file_upload" ]
        main:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!security", "!file_upload"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
